#!/bin/bash

# Distributed under the MIT license
# Copyright (c) 2014 Nicolae Ghimbovschi

VERSION=1.0.4
TEAMS=$1
TMPPROFILES=profiles
ADDITIONAL_PROVISIONING_PROFILES="/Users/`whoami`/Library/MobileDevice/Extra"
TEMPDIR=workdir
PROFILESDIR="/Users/`whoami`/Library/MobileDevice/Provisioning Profiles"
BACKUPDIR="/Users/`whoami`/Library/MobileDevice/Backup"

function usage() {
	echo "Usage: $0 TeamName1"
	echo "       $0 \"TeamName1, Team Name2, TeamName3\""
	echo ""
	echo "Options:"
	echo "       -v shows version"
	exit 0
}

function downloadAllProfiles() {
	echo "Downloading profiles for team: $1"
	export FASTLANE_PASSWORD="$APPLE_PASSWORD"
        sleep 30

        sigh download_all -u "$APPLE_USERNAME" -l "$1" --output_path . --skip_install

	if [ $? -ne 0 ]; then
    		echo "FAILED to download profiles for team $1"
		exit 1
	fi
}

function moveDownloadedFilesToTempDir() {
	PREFIX=$(echo "$1" | tr '\t ()' '_')
	for file in *.mobileprovision
	do
			FILENAME=$(echo "${file}" | sed s/*/_wildcard_/g)
	    mv "$file" "$TEMPDIR/${PREFIX}_${FILENAME}"
	done
}

function backupCurrentProfiles() {
	echo "Backing up current profiles to $BACKUPDIR"

	rm -fr "$BACKUPDIR"
	mkdir "$BACKUPDIR"
	mv "$PROFILESDIR/"*.mobileprovision "$BACKUPDIR"
}

function copyNewProfiles() {
	echo "Copying the new profiles"

	mv "$TEMPDIR"/* "$PROFILESDIR/"

	find "$ADDITIONAL_PROVISIONING_PROFILES" -name *.mobileprovision -exec cp "{}" "$PROFILESDIR/" \;
}

if [ $# -eq 0 ]
then
	usage
fi

if [[ "$1" == "-v" ]]
then
	echo "$VERSION"
	exit 0
fi

rm -fr "$TEMPDIR"
mkdir "$TEMPDIR"
mkdir -p "$PROFILESDIR"
mkdir -p "$BACKUPDIR"
mkdir -p "$ADDITIONAL_PROVISIONING_PROFILES"

OLDIFS=$IFS
IFS=,
set -- $TEAMS
for i 
do
  TEAM=$(echo $i | sed -e 's/^[ \t]*//')

  IFS=$OLDIFS

  downloadAllProfiles "$TEAM"
  moveDownloadedFilesToTempDir "$TEAM"

  IFS=,
done

IFS=$OLDIFS

backupCurrentProfiles
copyNewProfiles
